services:
  postgres:
    image: postgres:15
    container_name: truestate_db
    environment:
      POSTGRES_USER: truestate
      POSTGRES_PASSWORD: truestate
      POSTGRES_DB: truestatedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: